<?php
$config = $block->getLayout()->createBlock(\Magento\Config\Block\System\Config\Form::class);
$client_id = $config->getConfigValue('module/general/uma_client_id');
$client_secret = $config->getConfigValue('module/general/uma_client_secret');
$redirect_uri = $config->getConfigValue('module/general/uma_redirect_uri');
$authorize_url = $config->getConfigValue('module/general/uma_authorize_url');
$access_toekn_url = $config->getConfigValue('module/general/uma_access_token');
$get_profile_url = $config->getConfigValue('module/general/uma_profile_url');
$success_url = $config->getConfigValue('module/general/uma_redirect_after_login');
$baseurl = $config->getConfigValue('web/unsecure/base_url');

$authorization_code = $_GET['code'];

$data = array(
    'client_id' => $client_id,
    'client_secret' => $client_secret,
    'redirect_uri' => $redirect_uri,
    'code' => $authorization_code
 );

if (!empty($authorization_code)) {
    
    $data = array( 'client_id' => $client_id, 'client_secret' => $client_secret, 'redirect_uri' => $redirect_uri, 'code' => $authorization_code);
    $data_string = json_encode($data);
    $request = curl_init($access_toekn_url);
    curl_setopt($request, CURLOPT_HEADER, 0);
    curl_setopt($request, CURLOPT_RETURNTRANSFER, 1);
    curl_setopt($request, CURLOPT_HTTPHEADER, ['Content-Type: application/json']);
    curl_setopt($request, CURLOPT_CUSTOMREQUEST, "POST");
    curl_setopt($request, CURLOPT_POSTFIELDS, $data_string);
    curl_setopt($request, CURLOPT_FOLLOWLOCATION, true);
    $response = curl_exec($request); // execute curl fetch and store results in $response
    curl_close($request);
    $json_data = json_decode($response, true);

    $curl = curl_init();

    curl_setopt_array($curl, array(
      CURLOPT_URL => $get_profile_url,
      CURLOPT_RETURNTRANSFER => true,
      CURLOPT_ENCODING => '',
      CURLOPT_MAXREDIRS => 10,
      CURLOPT_TIMEOUT => 0,
      CURLOPT_FOLLOWLOCATION => true,
      CURLOPT_HTTP_VERSION => CURL_HTTP_VERSION_1_1,
      CURLOPT_CUSTOMREQUEST => 'POST',
      CURLOPT_POSTFIELDS => array('uid' => $json_data["uid"]),
      CURLOPT_HTTPHEADER => array('Authorization: Bearer '.$json_data["access_token"]),
    ));

    $customerinfo = curl_exec($curl);
    curl_close($curl);

    $customer_response = json_decode($customerinfo, true);
    $customerdata = $customer_response["response"];

    if ($customerdata["first_name"]) {
    	$firstName = $customerdata["first_name"];
    } else{
    	$firstName = "firstname";
    }

    if ($customerdata["last_name"]) {
        $lastName = $customerdata["last_name"];
    } else{
        $lastName = "lastname";
    }
       	
    $email =  $customerdata["email"];
    $uid = $customerdata["uid"]; 

    $objectManager = \Magento\Framework\App\ObjectManager::getInstance();
    $storeManager = $objectManager->get('\Magento\Store\Model\StoreManagerInterface');
    $websiteId = $storeManager->getStore()->getWebsiteId();
    $store = $storeManager->getStore();
    $password = password_generate(7);

    $customer = $objectManager->get('\Magento\Customer\Model\CustomerFactory')->create();
    $customer->setWebsiteId($websiteId);
    $customer->setStore($store);


    // Check if customer is already exists
    if ($customer->loadByEmail($email)->getId()) {
        custom_redirect($email,$success_url);
    } else {
        $customer->setEmail($email);
        $customer->setFirstname($firstName);
        $customer->setLastname($lastName);
        $customer->setPassword($password);
        $customer->setForceConfirmed(true);
        if($customer->save()){
            custom_redirect($email,$success_url);
        }
    }     
}

function password_generate($chars) {
  $data = '1234567890ABCDEFGHIJKLMNOPQRSTUVWXYZabcefghijklmnopqrstuvwxyz';
  return substr(str_shuffle($data), 0, $chars);
}

function custom_redirect($email, $success_url) {
    $objectManager = \Magento\Framework\App\ObjectManager::getInstance();
    $customerRepository = $objectManager->get('Magento\Customer\Api\CustomerRepositoryInterface'); 
    $customerRepo = $customerRepository->get($email);
    $customerFactory = $objectManager->get('Magento\Customer\Model\CustomerFactory');
    $customer = $customerFactory->create()->load($customerRepo->getId());
    $customerSession = $objectManager->get('Magento\Customer\Model\Session');
    $customerSession->setCustomerAsLoggedIn($customer);
    $redirect = $objectManager->get('\Magento\Framework\App\Response\Http');
    $redirect->setRedirect($success_url);
}

?>